services:
  postgres:
    image: postgres:latest
    container_name: UserApp-postgres
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TestUsers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/UserApp/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: UserApp-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: